# This is a basic workflow to help you get started with Actions

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - edited
  schedule:
  - cron: 0 0 1 * *
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Hello, World date!
      run: echo "Hello, World ! Today is $(date +'%m-%d-%y %H:%M:%S')"
