# This is a basic workflow to help you get started with Actions

name: ex03

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  alpine:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: alpine
    steps:
    - name: Show version
      run: lsb_release -rs
    
  archlinux:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - name: Show version
        run: lsb_release -rs
  
  fedora:
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - name: Version
        run: lsb_release -rs
