# This is a basic workflow to help you get started with Actions

name: ex04

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  nginx: 
    services:
      nginx:
        image: nginx
        ports:
          - 4242:80
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: get request
      run: curl -Is http://localhost:4242 | grep "HTTP/1.1 200 OK"
