# This is a basic workflow to help you get started with Actions

name: ex05

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    services:
      nginx:
        image: mrsquaare/nginx-htpasswd
        ports:
          - 4242:80
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: loign
      run: curl -Is -u $NGINX_USER:${{secrets.NGINX_PASSWORD}} http://localhost:4242 | grep "HTTP/1.1 200 OK"
      env:
        NGINX_USER: john
